---
project_id: amgen_SiEs08
output_dir: "/mnt/BioAdHoc/Groups/vd-vijay/cramirez/amg319/results/ab_demux"
sample_sheet: ./data/library_pairs.csv
# not necessary if you already have a sample_sheet, but this will create it with all feature barcode libraries
count_info:
  count_dir: /mnt/BioAdHoc/Groups/vd-vijay/cramirez/amg319/raw/NV035/count
  gex_data: filtered
  fbarcode_data: raw
demux:
  max_count_min: 100
  fold_change: 3
  subset_tags: random1234
# empty if you want to aggregate everything; or and aggregate.csv, or
# path to cellranger aggregations (containing aggr1/outs aggr2/outs); also a regex "sample1|sample2"
# args is for summary.R (exclude min_count, selected, and tag_str)
aggregation:
  source: "/mnt/BioAdHoc/Groups/vd-vijay/cramirez/fungal_allergy/raw/cellranger/aggr"
  args: "--metadata=/home/ciro/fungal_allergy/info/metadata_donor.csv~donor"
# Feature name structure; example is from Placebo-V-TSC5-C0305
# Always include 'donor' as one of them.
tag_str: treatment~donor~hashtag_n~hashtag_id
tag_delim: "-" # string use to separate the information in your hashtag names
job:
  walltime: 02:00:00
  mem: 10gb
  ppn: 1
  nodes: 1
  submit: yes # yes, no, or force
pipeline: ./
exec_r: Rscript
...
